### ISSUE TITLE
V0.15.0+ Raises TypeError on ESP32-ETH01

### ISSUE THREAD

**Issue by juldeus** [wled/WLED#4535]
### What happened?

Raises: TypeError: Cannot read properties of null (reading 'classList')

Tried it on two ESPs. Now running on v0.14.4 to not have the error.

### To Reproduce Bug

Installed Via Webinstaller.

### Expected Behavior

No Error

### Install Method

Binary from WLED.me

### What version of WLED?

v0.15.0 /v0.16.0 alpha

### Which microcontroller/board are you seeing the problem on?

Other

### Relevant log/trace output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ranvirgorai** [comment]
facing the same issue. It works fine when connected for the first time, but on the second attempt, it stops working and shows the error mentioned above

**Comment by simondib** [comment]
I had this issue when the data wire was connected to the wrong pin on my WT32-ETH01 board. Also have to make sure the Data GPIO value is correct in LED & Hardware setup.

**Comment by kilrah** [comment]
You probably are using a LED output pin that was robbed by the audioreactive usermod, go to usermods and set all pins for AR to Unused.

**Comment by rorosaurus** [comment]
Weird, I encountered this as well. I confirmed I wasn't using a pin conflicting with audioreactive usermod. But after a couple reboots the problem went away...

**Comment by 011V32** [comment]
I have the same problem.

**Comment by Arcitec** [comment]
`"TypeError: Cannot read properties of null (reading 'classList')"` is a HTML interface problem and means that the JavaScript code in WLED's UI tried to fetch an element, and then tried reading the `.classList` property of it. But the element was not found, therefore `null` was returned. And it's impossible to read a property of a `null` object.

In short it just means that code was trying to fetch an element and read its properties, but the element with such an ID did not exist on the WLED HTML page.

I am sure we can close this because there's no such issues in WLED 0.15.1 which is currently in release prep at #4701.

@blazoncek

**Comment by netmindz** [comment]
Fixed with https://github.com/wled/WLED/commit/2f31ff047d04546595cc7fd996bc04c56e575ffb

**Comment by mrv96** [comment]
The issue is still present defining `WLED_ENABLE_DMX` in both 0.15.0 and 0.15.1 versions.

**Comment by mrv96** [comment]
Update: issue is still present in branch `0_15_x` but solved in `main` branch

**Comment by softhack007** [comment]
it looks like this PR is needed in 0.15.x, too
* https://github.com/wled/WLED/pull/5205
